name: backend
description: A server app using the shelf package and Docker.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  globe_kv: ^1.0.0+1
  http: ^1.4.0
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
